# Generated by Django 4.2.11 on 2024-03-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoxData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("box_code", models.TextField(max_length=15)),
                ("latitude", models.IntegerField(null=True)),
                ("longitude", models.IntegerField()),
                ("length", models.IntegerField()),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("volume", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("box_code", models.TextField(primary_key=True, serialize=False)),
                ("delivery_man_code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("road_address", models.TextField(max_length=100)),
                ("detail_address", models.TextField(max_length=100)),
                ("phone", models.TextField(max_length=5)),
                ("date", models.DateField()),
            ],
        ),
    ]
