# Generated by Django 4.2.11 on 2024-04-14 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="boxdata",
            old_name="volume",
            new_name="sequence",
        ),
    ]
