# Generated by Django 4.2.11 on 2024-05-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxdata',
            name='loadsequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
