# Generated by Django 4.2.11 on 2024-04-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadedBoxData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_code', models.TextField(max_length=15)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('layer', models.IntegerField()),
                ('deliverySequence', models.IntegerField()),
                ('loadSeuqence', models.IntegerField()),
                ('positionX', models.IntegerField()),
                ('positionY', models.IntegerField()),
                ('positionZ', models.IntegerField()),
            ],
        ),
    ]
