# Generated by Django 4.2.11 on 2024-04-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Load', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadedboxdata',
            name='color',
            field=models.TextField(default='white', max_length=15),
            preserve_default=False,
        ),
    ]
