# Generated by Django 4.2.11 on 2024-04-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("dev_code", models.AutoField(primary_key=True, serialize=False)),
                ("dev_name", models.CharField(max_length=24)),
                ("dev_phone", models.CharField(max_length=12)),
                ("user_id", models.CharField(max_length=24, unique=True)),
                ("password", models.CharField(max_length=24, unique=True)),
                ("dev_ok", models.IntegerField()),
                ("work_ok", models.IntegerField()),
            ],
        ),
    ]
