# Generated by Django 4.2.11 on 2024-04-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_name', models.CharField(max_length=24)),
                ('dev_phone', models.IntegerField()),
                ('user_id', models.CharField(max_length=24, unique=True)),
                ('password', models.CharField(max_length=24, unique=True)),
                ('dev_ok', models.BinaryField()),
                ('work_ok', models.BinaryField()),
            ],
        ),
    ]
