# Generated by Django 4.2.11 on 2024-03-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Box", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("road_address", models.TextField(max_length=100)),
                ("detail_address", models.TextField(max_length=100)),
                ("phone", models.TextField(max_length=5)),
                ("length", models.IntegerField(max_length=5)),
                ("width", models.IntegerField(max_length=5)),
                ("height", models.IntegerField(max_length=5)),
            ],
        ),
    ]
