# Generated by Django 4.2.11 on 2024-03-25 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Box", "0003_alter_delivery_height_alter_delivery_length_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Delivery",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
